### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Guard13007** [Guard13007/52-Cards#1]
- [ ] Fix bugs with combining Decks.
- [ ] Make creating a Deck place it instead of grabbing it.
- [ ] Replace randomization with Love2D's randomization.
- [ ] Investigate integration with CONNECTION library.
- [ ] Add licensing info to code / add license info for libraries I'm using.
- [ ] Add inifile library to store screen size settings. (Make quick tutorial on how to do this??)
- [ ] Make card size scale with screen size. (current size should be for 1080p I think)
- [ ] Replace Deck.static.width / Deck.static.height with using Card (require Card in Deck to make this work).
- [ ] Make main menu. Options: Solo, Host, Connect, Tutorial
      - Solo: just launch into what we have now
      - Host: tells you your IP (and a note that this is a LAN IP, or find a way to actually grab your IP?)
      - Connect: asks for an IP (or will HTTP work??) and tries it, errors if error, does not attempt validation
      - Tutorial will be something I build later that goes through the basic controls (and maybe has you play Go Fish against an AI?)
- [ ] Bottom right corner: trash bin.
- [ ] Top left corner: mini-menu: grab a deck (w or w/o jokers), quit to main menu
- [ ] (requires multiplayer): bottom of screen central area: your hand: will show your Cards neatly lined up. Note that cards in here work like any other card, there's just extra code around them.
      - Top of screen will be another player's hand, but you can't see what they have obviously. You can still grab from their hand though. (These cards are like any other, except always face down to you, and have some extra code around them for auto aligning them as they are moved.)
- [ ] (for multiplayer) Note: If a card is picked from a hand, it is visible to THAT player, and invisible to the other. If a card is picked from anywhere else, it has whatever visibility it had.

**Comment by Dean4Devil** [comment]
- [ ] [Add faces to cards](http://sourceforge.net/projects/vector-cards/) ?

**Comment by Guard13007** [comment]
@Dean4Devil Eventually, something like that. The main reason I haven't included it on the todo list is I want to get the engine to a particular standard before I address the cards themselves. I'm additionally thinking about allowing for custom cards / additional card types or features or whatever, but whatever, I want to have the core flushed out before I get too crazy with additional things.

Another idea for example is animations when you shuffle, or place cards in decks, or whatever, and something to make it so that when you grab a card, it doesn't instantly snap to the mouse (so it looks smoother). These are polish ideas that I left out, but probably should've listed.
